services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: go_finance
      POSTGRES_PASSWORD: go_finance
      POSTGRES_DB: go_finance
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
